In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {'birds': ['Cranes', 'Cranes', 'plovers', 'spoonbills', 'spoonbills', 'Cranes', 'plovers', 'Cranes', 'spoonbills', 'spoonbills', 'Cranes'], 
        'age': [3.5, 4, 1.5, np.nan, 6, 3, 5.5, np.nan, 8, 4, 3.5], 'visits': [2, 4, 3, 4, 3, 4, 2, 2, 3, 2, 2], 
        'priority': ['yes', 'yes', 'no', np.nan, 'no', 'no', 'no', 'yes', 'no', 'no','yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']

### `Q-1:` 
i. Create a DataFrame birds from the above dictionary data which has the index labels. 

ii. Show Alternate rows of the dataframe.

In [3]:
# 1i)
df=pd.DataFrame(data,index=labels)
df

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  NaN       4      NaN
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k      Cranes  3.5       2      yes

In [4]:
# 1ii)
df.iloc[::2,::]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
i  spoonbills  8.0       3       no
k      Cranes  3.5       2      yes

### `Q-2:` 
i. Show only rows [1st, 3rd, 7th] from columns ['bird', 'age']

ii. Select rows where the number of visits is less than 4.

In [5]:
# 2i)
df.iloc[[1,3,7]][['birds','age']]

        birds  age
b      Cranes  4.0
d  spoonbills  NaN
h      Cranes  NaN

In [6]:
# 2ii)
df[df['visits']<4]

        birds  age  visits priority
a      Cranes  3.5       2      yes
c     plovers  1.5       3       no
e  spoonbills  6.0       3       no
g     plovers  5.5       2       no
h      Cranes  NaN       2      yes
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no
k      Cranes  3.5       2      yes

### `Q-3:` 
i. Select all rows with nan values in age and visits column.

ii. Fill nan with respective series mode value.

In [7]:
# 3i)
df[df['age'].isnull() | df['visits'].isnull()]

        birds  age  visits priority
d  spoonbills  NaN       4      NaN
h      Cranes  NaN       2      yes

In [8]:
df.age.fillna(df.age.mode()[0],inplace=True)

C:\Users\khadk\AppData\Local\Temp\ipykernel_16388\2456331915.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.age.fillna(df.age.mode()[0],inplace=True)

### `Q-4`
i. Find the total number of visits of the bird Cranes

ii. Find the number of each type of birds in dataframe.

iii. Print no of duplicate rows

iv. Drop Duplicates rows and make this changes permanent. Show dataframe after changes.

In [9]:
# 4i)
df[df['birds']=="Cranes"].visits.sum()

np.int64(14)

In [10]:
# 4ii)
df['birds'].value_counts()

birds
Cranes        5
spoonbills    4
plovers       2
Name: count, dtype: int64

In [11]:
# 4iii)
df[df.duplicated()]

    birds  age  visits priority
h  Cranes  3.5       2      yes
k  Cranes  3.5       2      yes

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df

        birds  age  visits priority
a      Cranes  3.5       2      yes
b      Cranes  4.0       4      yes
c     plovers  1.5       3       no
d  spoonbills  3.5       4      NaN
e  spoonbills  6.0       3       no
f      Cranes  3.0       4       no
g     plovers  5.5       2       no
i  spoonbills  8.0       3       no
j  spoonbills  4.0       2       no