In [1]:
import pandas as pd

df = pd.DataFrame({
    "match_id": [1,1,1,2,2,3,3,3,3],
    "player": ["Kohli","Smith","Root","Kohli","Warner",
               "Smith","Root","Kohli","Buttler"],
    "runs": [45,60,12,80,10,100,5,23,44],
    "team": ["IND","AUS","ENG","IND","AUS",
             "AUS","ENG","IND","ENG"]
})

print(df)

   match_id   player  runs team
0         1    Kohli    45  IND
1         1    Smith    60  AUS
2         1     Root    12  ENG
3         2    Kohli    80  IND
4         2   Warner    10  AUS
5         3    Smith   100  AUS
6         3     Root     5  ENG
7         3    Kohli    23  IND
8         3  Buttler    44  ENG

“Find the total runs scored by players who have ever scored ≥ 50 runs in any match, but only in matches where the opponent team is also in a shortlist (['AUS','ENG']).”

In [2]:
opponent_team=~df['team'].isin(['AUS','ENG'])
opponent_team

0     True
1    False
2    False
3     True
4    False
5    False
6    False
7     True
8    False
Name: team, dtype: bool

In [3]:
players_fifty=df[df['runs']>50]['player'].unique()
players_fifty

array(['Smith', 'Kohli'], dtype=object)

In [4]:
players=df['player'].isin(players_fifty)
players

0     True
1     True
2    False
3     True
4    False
5     True
6    False
7     True
8    False
Name: player, dtype: bool

In [5]:
df[opponent_team & players]

   match_id player  runs team
0         1  Kohli    45  IND
3         2  Kohli    80  IND
7         3  Kohli    23  IND

You have a df of student grades with columns ['name', 'subject', 'grade'].
Find all rows where subject is either "Math" or "Science".

In [6]:
df = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "subject": ["Math", "English", "Science", "History", "Math"],
    "grade": [85, 70, 90, 65, 95]
})
print(df)

      name  subject  grade
0    Alice     Math     85
1      Bob  English     70
2  Charlie  Science     90
3    David  History     65
4      Eva     Math     95

In [7]:
df[df['subject'].isin(['Math','Science'])]

      name  subject  grade
0    Alice     Math     85
2  Charlie  Science     90
4      Eva     Math     95

Given a df with sales data ['product', 'region', 'sales']:Extract all rows where region is not in ['North', 'South'].Now, from those rows, keep only the products "A" or "B".

In [8]:
df = pd.DataFrame({
    "product": ["A", "B", "C", "D", "A", "B"],
    "region": ["North", "South", "East", "West", "South", "East"],
    "sales": [200, 150, 300, 400, 250, 350]
})
print(df)

  product region  sales
0       A  North    200
1       B  South    150
2       C   East    300
3       D   West    400
4       A  South    250
5       B   East    350

In [9]:
new_df=df[~df['region'].isin(['North', 'South'])]
new_df

  product region  sales
2       C   East    300
3       D   West    400
5       B   East    350

In [10]:
new_df[new_df['product'].isin(['B','A'])]

  product region  sales
5       B   East    350